QLKS/QLKS/Areas/Admin/Controllers/ChiTietPhongController.cs
using Data_Access.ChiTietPhong;
using Data_Access.DTO;
using System.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
namespace QLKS.Areas.Admin.Controllers
{
    public class ChiTietPhongController : Controller
    {
        ConnectClass cc = new ConnectClass();
        // GET: Admin/ChiTietPhong
        public ActionResult Index()
        {
            ViewBag.var1 = new SelectList(cc.Loadphong(), "ID", "TENPHONG");
            return View(cc.LoadChiTietPhong());
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.var2 = new SelectList(cc.LoadThuePhong(0), "ID", "PHONG");

            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, CHITIETPHONG ct )
        {
            if (ModelState.IsValid)
            {
                int num;
                int.TryParse(collection["var2"], out num);
                ct.IDCT = num;
                
                if (cc.Create(ct))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Lỗi khi thêm");
                }
            }
            ViewBag.var2 = new SelectList(cc.LoadThuePhong(0), "ID", "PHONG");
            return View();
        }

    }
}

QLKS/QLKS/Areas/Admin/Controllers/DatPhongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLKS.Areas.Admin.Controllers
{
    public class DatPhongController : Controller
    {
      
        // GET: Admin/DatPhong
        public ActionResult Index()
        {
            return View();
        }
    }
}

QLKS/QLKS/Areas/Admin/Controllers/SDDVController.cs
using Data_Access.DTO;
using Data_Access.Sddv;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLKS.Areas.Admin.Controllers
{
    public class SDDVController : Controller
    {
        // GET: Admin/SDDV
        ConnectClass cc = new ConnectClass();
        public ActionResult Index()
        {
            return View(cc.LoadSDDV());
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.var1 = new SelectList(cc.LoadThuePhong(), "ID", "PHONG");
            ViewBag.var2 = new SelectList(cc.LoadDichVu(), "ID", "TEN");
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection,SDDV sddv)
        {
            if(ModelState.IsValid)
            {
                int num, num2;
                int.TryParse(collection["var1"], out num);
                sddv.IDCT = num;
                int.TryParse(collection["var2"], out num2);
                sddv.IDDV = num2;
                if (cc.Create(sddv))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Lỗi khi thêm");
                }
            }
            ViewBag.var1 = new SelectList(cc.LoadThuePhong(), "ID", "PHONG");
            ViewBag.var2 = new SelectList(cc.LoadDichVu(), "ID", "TEN");
            return View();
        }

        public ActionResult Delete(int id)
        {
            cc.Delete(id);
            return RedirectToAction("Index");
        }
        
    }
}

QLKS/QLKS/Areas/Admin/Controllers/Test1Controller.cs
using Data_Access.DTO;
using Data_Access.ThuePhong;
using QLKS.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace QLKS.Areas.Admin.Controllers
{
    public class Test1Controller : Controller
    {
        ConnectClass cc = new ConnectClass();

        List<SelectListItem> loaiPhong = new List<SelectListItem>();
        // GET: Admin/Test1
        public ActionResult Index()
        {
            return View(cc.LoadThuePhong());
        }
        public SelectList SetViewBag()
        {
            List<LOAIPHONG> loaiPhong1 = cc.LoadLoaiPhong();
            foreach (LOAIPHONG item in loaiPhong1)
            {
                loaiPhong.Add(new SelectListItem { Text = item.TEN, Value = item.ID.ToString() });
            }
            return new SelectList(loaiPhong, "Value", "Text");
        }
        [HttpGet]
        public ActionResult Test()
        {
            ViewBag.var1 = SetViewBag();
            ViewBag.var2 = new SelectList(cc.LoadPhong(0), "ID", "TENPHONG");
            return View();
        }
        [HttpPost]
        public ActionResult Test(FormCollection collect,PhieuThue phieuthue)
        {
            if(ModelState.IsValid)
            {
                NHANVIEN ad = (NHANVIEN)Session["TaiKhoanAdmin"];
                phieuthue.IDNhanVien = ad.ID ;
                var id = collect["var2"].ToString();
                if (phieuthue.TenCongTy == null)
                    phieuthue.TenCongTy = "";
                if (phieuthue.SDT == null)
                    phieuthue.SDT = "";
                if (phieuthue.DiaChi == null)
                    phieuthue.DiaChi = "";
                if(cc.Test(int.Parse(id),phieuthue.IDNhanVien,phieuthue.CMND,phieuthue.Ten,phieuthue.DiaChi,phieuthue.SDT,phieuthue.TenCongTy))
                {
                    
                    return RedirectToAction("ThemNguoi",new { id = cc.GetID() });
                }
            }
            return View();
        }
        
        [HttpPost]
        public ActionResult LayPhong(int _id)
        {
            PHONG daata = cc.PGetPhong(_id);
            return Json(new { id = daata.ID, tenphong = daata.TENPHONG });
        }



        public ActionResult GetDropDownTenPhong(int id)
        {
            var data = cc.LoadPhong(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Thanhtoan(int id)
        {
            return View(cc.HoaDon(id));
        }
        [HttpPost]
        public ActionResult Thanhtoan(FormCollection Collection,ThanhToanPhong thanhtoan)
        {
            if(ModelState.IsValid)
            {
                
                //int.TryParse(Collection["tong"].ToString(), out tong);
                //thanhtoan.TongTien = tong;
                if(cc.ThanhToan(cc.HoaDon(thanhtoan.ID)))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Lỗi");
                }
            }
            return View();
        }
        public ActionResult Detail (int id)
        {
            return View(cc.HoaDon(id,1));
        }
        public ActionResult DetailPhong(int id)
        {
            return View(cc.HoaDon(id, 0));
        }
        [HttpGet]
        public ActionResult ThemNguoi(int id)
        {
            CHITIETPHONGLOAD tam = new CHITIETPHONGLOAD();
            var t = cc.HoaDon(id);
            tam.TenPhong = t.phong.TENPHONG;
            tam.IDCT = t.ID;
            return View(tam);
        }
        [HttpPost]
        public ActionResult ThemNguoi(CHITIETPHONGLOAD ctp)
        {
            if(ModelState.IsValid)
            {
                if(cc.Create(ctp))
                {
                    return RedirectToAction("DetailPhong",new { id = ctp.IDCT});
                }
                else
                {
                    ModelState.AddModelError("","Quá số người quy định");
                }
            }
            return View(ctp);
        }
        [HttpGet]
        public ActionResult DichVu(int id)
        {
            ViewBag.var2 = new SelectList(cc.LoadDichVu(), "ID", "TEN");
            SDDVLOAD tam = new SDDVLOAD();
            var t = cc.HoaDon(id, 0);
            tam.IDCT = t.ID;
            tam.PHONG = t.phong.TENPHONG;
            return View(tam);
        }

        public ActionResult DichVu(SDDV sDDV,FormCollection collection)
        {
            if(ModelState.IsValid)
            {
                int num2;
                int.TryParse(collection["var2"], out num2);
                sDDV.IDDV = num2;
                if (cc.Create(sDDV))
                {
                    return RedirectToAction("DetailPhong",new { id = sDDV.IDCT});
                }
                else
                {
                    ModelState.AddModelError("", "Lỗi khi thêm");
                }
            }
            return View();

        }
    }
}

QLKS/QLKS/Areas/Admin/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.Data.Sql;
using Data_Access.DAO;
using Data_Access.DTO;
using Data_Access.ThuePhong;
using QLKS.Areas.Admin.Models;

namespace QLKS.Areas.Admin.Controllers
{
    public class TestController : Controller
    {
        ConnectClass cc = new ConnectClass();
        // GET: Admin/Test
        List<SelectListItem> loaiPhong = new List<SelectListItem>();
        List<SelectListItem> phong = new List<SelectListItem>();
        int idMaPhieu;
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.var1 = SetViewBag();
            List<PHONG> phong = cc.LoadPhong(0);
            ViewBag.var2 = new SelectList(phong, "ID", "TENPHONG");
            ///ViewBag.var2 = phong;
            ///ViewBag.var3 = SoPhong(0); 
            //ViewData["var3"] = SoPhong(0);
            return View();
        }
        [HttpPost]
        public ActionResult Index(LOAIPHONG loaiphong,TestDK test)
        {
            if(ModelState.IsValid)
            {
                ViewBag.var1 = new SelectList(cc.LoadLoaiPhong(), "ID", "TEN");// load loai phong len 
                ViewBag.var2 = new SelectList(cc.LoadPhong(), "ID", "TENPHONG");

                ViewBag.id = new SelectList(loaiPhong, "id", "tenPhong", loaiphong.ID);
                idMaPhieu = cc.DangKi(test.CMND, test.TenDK, test.DiaChi, test.SDT, test.TenCongTy);
                return Redirect("Step2");
            }
            return View();
        }
        public ActionResult GetPhong(int id)
        {
            var daata = cc.LoadPhong(id);
            return Json(daata, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult LayPhong(int _id)
        {
            PHONG daata = cc.PGetPhong(_id);
            return Json(new { id = daata.ID, tenphong = daata.TENPHONG });
        }

        public ActionResult Step2()
        {
            return View();
        }









        public SelectList SetViewBag()
        {
            List<LOAIPHONG> loaiPhong1 = cc.LoadLoaiPhong();
            foreach(LOAIPHONG item in loaiPhong1)
            {
                loaiPhong.Add(new SelectListItem { Text = item.TEN,Value = item.ID.ToString() });
            }
            ///return new SelectList(loaiPhong, "ID", "Text","TEN");
            return new SelectList(loaiPhong, "Value", "Text", "ID");
        }   
        public JsonResult Phong(int id)
        {
            List<PHONG> phong1 = cc.LoadPhong(id);
            foreach(PHONG item in phong1)
                phong.Add(new SelectListItem { Text = item.TENPHONG, Value = item.ID.ToString() });
            ViewBag.var2 = new SelectList(phong, "ID", "TENPHONG");
            return Json(phong, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetDropDownTenPhong(int id)
        {
            var data = cc.LoadPhong(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

    }
}

QLKS/QLKS/Areas/Admin/Controllers/ThuePhongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data_Access.DTO;
using Data_Access.ThuePhong;
using QLKS.Areas.Admin.Models;

namespace QLKS.Areas.Admin.Controllers
{
    public class ThuePhongController : Controller
    {
        // GET: Admin/ThuePhong
        public ConnectClass cc = new ConnectClass();
        List<SelectListItem> loaiPhong = new List<SelectListItem>();

        // GET: ThuePhongs
        public ActionResult Index()
        {
            ///var thuePhongs = db.ThuePhongs.Include(t => t.KhachHang).Include(t => t.phong);
            List<THUEPHONG> thuephong = cc.LoadThuePhong();
            return View();
        }

        // GET: ThuePhongs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            THUEPHONG thuephong = cc.SearchThuePhong(id);
            if (thuephong == null)
            {
                return HttpNotFound();
            }
            return View(thuephong);
        }

        // GET: ThuePhongs/Create
        public ActionResult Create()
        {
            
            ViewBag.loaiphong = SetViewBag();
            ///ViewBag.idKhach = new SelectList(db.KhachHangs, "id", "ten");            
            ///ViewBag.idNV = new SelectList(db.nhanViens, "id", "tenHienThi");
            return View();
        }
        public SelectList SetViewBag()
        {
            List<LOAIPHONG> loaiPhong1 = cc.LoadLoaiPhong();
            foreach (LOAIPHONG item in loaiPhong1)
            {
                loaiPhong.Add(new SelectListItem { Text = item.TEN, Value = item.ID.ToString() });
            }
            return new SelectList(loaiPhong, "id", "ten");
        }
        // POST: ThuePhongs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TenDK,CMND,DiaChi,SDT,TenCongTy,DsLoaiPhong,DsPhong")] TestDK thuePhong)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            ViewBag.loaiphong = SetViewBag();
            return View(thuePhong);
        }

        // GET: ThuePhongs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            /*ThuePhong thuePhong = db.ThuePhongs.Find(id);
            if (thuePhong == null)
            {
                return HttpNotFound();
            }
            ///ViewBag.idKhach = new SelectList(db.KhachHangs, "id", "ten", thuePhong.idKhach);*/

            //ViewBag.idPhong = new SelectList(db.phongs, "id", "tenPhong", thuePhong.idPhoSng);
            //return View(thuePhong);
            return View();
        }

        // POST: ThuePhongs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TenDK,CMND,DiaChi,SDT,TenCongTy,DsLoaiPhong,DsPhong")] TestDK thuePhong)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(thuePhong).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            ///ViewBag.idKhach = new SelectList(db.KhachHangs, "id", "ten", thuePhong.idKhach);
            ///ViewBag.idPhong = new SelectList(db.phongs, "id", "tenPhong", thuePhong.idPhong);
            ///return View(thuePhong);
            return View();
        }

        // GET: ThuePhongs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ///ThuePhong thuePhong = db.ThuePhongs.Find(id);
            /*if (thuePhong == null)
            {
                return HttpNotFound();
            }
            return View(thuePhong);*/
            return View();
        }

        // POST: ThuePhongs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            /*ThuePhong thuePhong = db.ThuePhongs.Find(id);
            db.ThuePhongs.Remove(thuePhong);
            db.SaveChanges();*/
            return RedirectToAction("Index");
        }
        public ActionResult GetDropDownTenPhong(int id)
        {
            ///var data = db.phongs.Where(s => s.idLoai.Equals(id)).Select(s => new { s.id, s.tenPhong }).ToArray();
            var data = cc.LoadPhong(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ///db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLKS/QLKS/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title> Diamond_Hotel </title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Asset/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Asset/vendor/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <!-- MetisMenu CSS -->
    <link href="~/Asset/vendor/metisMenu/metisMenu.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/Asset/dist/css/sb-admin-2.css" rel="stylesheet" />
    <link href="~/Asset/dist/css/sb-admin-2.min.css" rel="stylesheet" />
    <!-- Morris Charts CSS -->
    <link href="~/Asset/vendor/morrisjs/morris.css" rel="stylesheet" />
    <!-- Custom Fonts -->
    <link href="~/Asset/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0; background-color: #fae0e0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="color:black; padding-bottom: 10px" href="#">
                    <p>
                        <i class="fa fa-home"></i> Hệ thống Quản Lí Khách Sạn &nbsp; | 
                    </p>
                   
                </a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <li style="padding-right:400px">
                    <h5> <i class="fa fa-heart-o"></i> Address: 211 Hàm Nghi, phường Bến Nghé, Quận 1  </h5>
                </li>
                <!-- /.dropdown -->
               <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i>@Session["ABC"].ToString()</a>
               </li>
               <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
               </li>
               <li>
                            <p><i class="fa fa-sign-out fa-fw"></i>@Html.ActionLink("Logout","Logout","Login")</p>
               </li>
                    
                    <!-- /.dropdown-user -->
               
               
                <!-- /.dropdown -->
            </ul>
            
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li style=" padding-left:15px; padding-top: 10px">

                        </li>
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>

                        <li>
                            <br />
                        </li>
                        <li style="padding-left:15px; padding-top: 7px">
                            <p><i class="fa fa-list"></i> @Html.ActionLink("Danh Sách Phòng Thuê", "Index", "Test1")  </p>
                        </li>
                        <li style="padding-left:15px; padding-top: 7px">
                            <p><i class="fa fa-glass"></i> @Html.ActionLink("Sử Dụng Dịch Vụ", "Index", "SDDV")  </p>
                        </li>
                        <li style="padding-left:15px; padding-top: 7px">
                            <p><i class="fa fa-rss"></i> @Html.ActionLink("Dịch Vụ", "Index", "DichVu")  </p>
                        </li>

                        <li style="padding-left:15px; padding-top: 7px">
                            <p><i class="fa fa-user"></i> @Html.ActionLink("Nhân Viên", "Index", "NhanVien")  </p>
                        </li>

                        <li style=" padding-left:15px; padding-top: 7px">
                            <p><i class="glyphicon glyphicon-user"></i> @Html.ActionLink("Khách Hàng", "Index", "ChiTietPhong")  </p>
                        </li>

                        <li style=" padding-left:15px; padding-top: 7px">
                            <p><i class="fa fa-star-half-full"></i> @Html.ActionLink("Danh Sách Phòng", "Index", "DanhSachPhong")  </p>
                        </li>
                        <li style=" padding-left:15px; padding-top: 7px">
                            <p><i class="fa fa-calendar"></i> @Html.ActionLink("Loại Phòng", "Index", "LoaiPhong")  </p>
                        </li>

                        <li style=" padding-left:15px; padding-top: 7px">
                            <p><i class="fa fa-calendar"></i> @Html.ActionLink("Chi Tiết Phòng", "Index", "ChiTietPhong")  </p>
                        </li>
                        <li style=" padding-left:15px; padding-top: 7px">
                            <p><i class="fa fa-wrench fa-fw"></i> @Html.ActionLink("Tài sản thiết bị", "Index", "TaiSan")  </p>
                        </li>

                        <li style=" padding-left:15px; padding-top: 7px">
                            <p><i class="fa fa-file-text"></i> @Html.ActionLink("Báo Cáo Thống Kê", "Index", "Test1")  </p>
                        </li>



                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <div class="page-header">
                        <h3>
                            <img style="width:90px ; height:80px" src="~/Asset/images/kimcuong.jpg" />    @Html.ActionLink(" Diamond Hotel", "Test", "Test1") &nbsp; |
                            <img style="width:30px ; height:30px" src="~/Asset/images/ngsao2.png" /> <img style="width:30px ; height:30px" src="~/Asset/images/ngsao2.png" />    <img style="width:30px ; height:30px" src="~/Asset/images/ngsao2.png" />  <img style="width:30px ; height:30px" src="~/Asset/images/ngsao2.png" />

                        </h3>

                    </div>
                    <div>
                        @RenderBody()
                    </div>
                </div>
                <!-- /.col-lg-12 -->
                <!-- /.row -->
                <!-- /.panel-body -->



            </div>
        </div>
        <!-- /#page-wrapper -->
    </div>


    <link href="~/Content/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <!--boostrap-->
    <!--hàm js để đưa datatable vs table id = "table_id" datatable có sẵn hết-->
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable({
                "pagingType": "full_numbers",
            });
        });
    </script>

    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/Asset/vendor/jquery/jquery.min.js"></script>
    <script src="~/Asset/vendor/jquery/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Asset/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <link href="~/Asset/vendor/metisMenu/metisMenu.css" rel="stylesheet" />
    <link href="~/Asset/vendor/metisMenu/metisMenu.min.css" rel="stylesheet" />

    <script src="~/Asset/vendor/metisMenu/metisMenu.js"></script>
    <script src="~/Asset/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/Asset/vendor/raphael/raphael.min.js"></script>
    <script src="~/Asset/vendor/morrisjs/morris.min.js"></script>
    <script src="~/Asset/data/morris-data.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Asset/dist/js/sb-admin-2.min.js"></script>
    @RenderSection("jsFooter1", required: false)

    <script>
        function myFunction() {
            // ajax là dùng để load bất đồng bộ//
            // hàm này gọi ajax nó truyền vào url lấy phòng theo id
            $.ajax({
                url: '/Test1/GetDropDownTenPhong/' + $('#var1 :selected').val(),
                type: 'POST',
                dataType: 'json',

                success: function (data) {
                    // khi load thành công thì nó vào chỗ này

                    $(".tenphong").html('<option value="">Vui lòng chọn phòng</option>');// dùng để thêm option vào dropdownlist
                    $.each(data, function () {
                        //this.id là để lấy id tương tự this.name là lấy name // 
                        $(".tenphong").append('<option value="' + this.ID + '">' + this.TENPHONG + '</option>');
                    });
                },

                error: function (err) {

                    alert("Có lỗi, vui lòng load lại !");
                }
            })
        }
    </script>
    <link href="~/Content/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <!--boostrap-->
    <!--hàm js để đưa datatable vs table id = "table_id" datatable có sẵn hết-->
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable({
                "pagingType": "full_numbers",
            });
        });
    </script>
</body>
</html>

QLKS/QLKS/Areas/Admin/Views/Shared/_LayoutAdminHeader.cshtml
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">SB Admin</a>
</div>